-
  name: Title
  editable: True
  step: 1
  questions:
    - titleSpecialists
    - titleOutcomesParticipants
-
  name: Specialist role
  editable: True
  step: 1
  questions:
    - specialistRole
-
  name: Location
  editable: True
  step: 1
  questions:
    - locationOutcomes
    - locationSpecialists
    - locationParticipants
-
  name: Description of work
  editable: True
  step: 1
  description: |
    This will help suppliers decide whether to apply.
  questions:
    - organisation
    - backgroundInformation
    - outcome
    - specialistWork
    - endUsers
    - earlyMarketEngagement
    - workAlreadyDone
    - phase
    - existingTeamOutcomes
    - existingTeamSpecialists
    - researchRounds
    - participantsPerRound
    - researchDates
    - researchFrequency
    - researchOutOfHours
    - researchAddress
    - accessRestrictions
    - participantSpecification
    - participantAccessibilityNeeds
    - researchPlan
    - workplaceAddress
    - workingArrangements
    - securityClearance
    - startDate
    - contractLength
    - additionalTerms
    - budgetRangeOutcomesParticipants
    - budgetRangeSpecialists
    - summary

-
  name: Shortlist and evaluation criteria
  editable: True
  step: 2
  description: |
    1\. Shortlist

    After you’ve published your requirements, suppliers will apply and tell you:

    - when they can start work
    - if they have the essential skills and experience
    - which nice-to-have skills and experience they have

    You can shortlist suppliers who:

    - can start work when you need them to
    - meet all the essential skills and experience
    - provide the most nice-to-have skills and experience

    [Read how to shortlist](https://whitehall-admin.publishing.service.gov.uk/guidance/how-to-shortlist-digital-outcomes-and-specialists-suppliers?cachebust=1459760956&preview=609577)

    2\. Evaluate

    To find the most suitable supplier, you must evaluate your shortlist on:

    - technical competence, eg how well the supplier’s skills or proposal meet your needs
    - cultural fit, eg how the supplier will work in your organisation
    - the price of the proposal

  questions:
    - numberOfSuppliersOutcomes
    - weightingOutcomes
    - technicalCompetenceCriteriaOutcomes
    - culturalFitCriteriaOutcomes
    - priceCriteria
    - evaluationTypeOutcomes

-
  name: Shortlist and evaluation criteria
  editable: True
  step: 2
  description: |
    1\. Shortlist

    After you’ve published your requirements, specialists will apply and tell you:

    - when they can start work
    - if they have the essential skills and experience
    - which nice-to-have skills and experience they have

    You can shortlist suppliers who:

    - can start work when you need them to
    - meet all the essential skills and experience
    - provide the most nice-to-have skills and experience

    [Read how to shortlist](https://whitehall-admin.publishing.service.gov.uk/guidance/how-to-shortlist-digital-outcomes-and-specialists-suppliers?cachebust=1459760956&preview=609577)

    2\. Evaluate

    To find the most suitable supplier, you must evaluate your shortlist on:

    - technical competence, eg how well the specialist’s skills or proposal meet your needs
    - cultural fit, eg how the supplier will work in your organisation
    - the price of the proposal

  questions:
    - numberOfSuppliersSpecialists
    - weightingSpecialists
    - technicalCompetenceCriteriaSpecialists
    - culturalFitCriteriaSpecialists
    - evaluationTypeSpecialists

-
  name: Shortlist and evaluation criteria
  editable: True
  step: 2
  description: |
    1\. Shortlist

    After you’ve published your requirements, suppliers will apply and tell you:

    - when they can start work
    - if they have the essential skills and experience
    - which nice-to-have skills and experience they have

    You can shortlist suppliers who:

    - can start work when you need them to
    - meet all the essential skills and experience
    - provide the most nice-to-have skills and experience

    [Read how to shortlist](https://whitehall-admin.publishing.service.gov.uk/guidance/how-to-shortlist-digital-outcomes-and-specialists-suppliers?cachebust=1459760956&preview=609577)

    2\. Evaluate

    To find the most suitable supplier, you must evaluate your shortlist on:

    - technical competence, eg how well the supplier’s skills or proposal meet your needs
    - availability, whether the supplier can recruit user research participants when you need them.
    - the price of the proposal

  questions:
    - numberOfSuppliersParticipants
    - weightingParticipants
    - technicalCompetenceCriteriaParticipants
    - evaluationTypeParticipants

-
  name: Describe question and answer session
  editable: True
  step: 3
  description: |
    While the application period is open, you need to reply to all questions suppliers ask about your requirements.

    When a supplier asks a question, you’ll be sent an email to the email address you registered with.

    You’ll need to post all questions and answers on the Digital Marketplace so that all suppliers can see them.

    Providing a question and answer session means you can explain your needs and answer any questions quickly.
  questions:
    - questionAndAnswerSessionDetails
